### PR TITLE
Fixed useChryslerMapCorrection

### PR DESCRIPTION
**Pull request by FlashStopFall**
ChryslerMapCorrection was broken when refactoring code in commit 419973f (Jun-6-2023). Code that used to be in functions.h got moved to trip_measurement.ino, and code that used to be in trip_measurement.ino got moved to trip_measurement.h. Moving them back allows useChryslerMapCorrection to compile.

I also changed EEPROM.h to eeprom.h to allow compiling on linux.

What caused useChryslerMapCorrection to break:
The code from functions.h was moved to trip_measurement.ino, which caused "error: 'prgmCalculateMAPpressure' was not declared in this scope" because the IDE couldn't access those function definitions ("#include functions.h" in mpguino_tav.ino).
The code from trip_measurement.ino was moved to trip_measurement.h, causing "Compilation error: 'tPressureChannel' was not declared in this scope".

### CODE REVIEW

**Comment by tvago1972** [comment]
reference changes made separately
