### ISSUE TITLE
"useChryslerMAPCorrection" Is Broken

### ISSUE THREAD

**Issue by FlashStopFall** [tvago1972/MPGuino#28]
`useChryslerMAPCorrection` has been broken since commit 419973fb81e7e9d3ed486eb82919e8eb0f996e6e, with the last working version being commit a50af8e33a183f43dc8bc68bb9c07947d56f5f4b. (Arduino nano 328p, legacy board, legacy LCD, legacy buttons, but it doesn't compile for any board).

Commit 419973f (above) gives a different error (`Compilation error: 'prgmCalculateMAPpressure') was not declared in this scope` than the current main/develop build (`Compilation error: 'tPressureChannel' was not declared in this scope`). The earliest commit I happened to track this to was e6930e7b67047de2dfb29e1ac8187c2ea82972db.

It appears some code was moved out of `trip_measurement.h` and `functions.h` into `trip_measurement.ino`, and that broke things.

**Comment by FlashStopFall** [comment]
Fixed in pull request #29.
